// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         companyId: "company_id",
 *         status: "cancelled",
 *         limit: 1000000,
 *         offset: 1000000
 *     }
 */
export interface ListScheduledCheckoutsRequest {
    companyId?: string;
    status?: Schematic.ScheduledCheckoutStatus;
    /** Page limit (default 100) */
    limit?: number;
    /** Page offset (default 0) */
    offset?: number;
}
