// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         q: "q",
 *         webhook_id: "webhook_id",
 *         limit: 1,
 *         offset: 1
 *     }
 */
export interface CountWebhookEventsRequest {
    ids?: string | string[];
    q?: string;
    webhook_id?: string;
    /** Page limit (default 100) */
    limit?: number;
    /** Page offset (default 0) */
    offset?: number;
}
