// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index";

export interface GetSingleLicenseResponse {
    data: Schematic.LicenseResponseData;
    /** Input parameters */
    params: Record<string, unknown>;
}
