// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";
import { EntitlementValueType } from "../../../../types/EntitlementValueType";
import { UpdateCompanyOverrideRequestBodyMetricPeriod } from "../../types/UpdateCompanyOverrideRequestBodyMetricPeriod";
import { UpdateCompanyOverrideRequestBodyMetricPeriodMonthReset } from "../../types/UpdateCompanyOverrideRequestBodyMetricPeriodMonthReset";

export const UpdateCompanyOverrideRequestBody: core.serialization.Schema<
    serializers.UpdateCompanyOverrideRequestBody.Raw,
    Schematic.UpdateCompanyOverrideRequestBody
> = core.serialization.object({
    creditConsumptionRate: core.serialization.property(
        "credit_consumption_rate",
        core.serialization.number().optional(),
    ),
    expirationDate: core.serialization.property("expiration_date", core.serialization.date().optional()),
    metricPeriod: core.serialization.property("metric_period", UpdateCompanyOverrideRequestBodyMetricPeriod.optional()),
    metricPeriodMonthReset: core.serialization.property(
        "metric_period_month_reset",
        UpdateCompanyOverrideRequestBodyMetricPeriodMonthReset.optional(),
    ),
    note: core.serialization.string().optional(),
    valueBool: core.serialization.property("value_bool", core.serialization.boolean().optional()),
    valueCreditId: core.serialization.property("value_credit_id", core.serialization.string().optional()),
    valueNumeric: core.serialization.property("value_numeric", core.serialization.number().optional()),
    valueTraitId: core.serialization.property("value_trait_id", core.serialization.string().optional()),
    valueType: core.serialization.property("value_type", EntitlementValueType),
});

export declare namespace UpdateCompanyOverrideRequestBody {
    export interface Raw {
        credit_consumption_rate?: number | null;
        expiration_date?: string | null;
        metric_period?: UpdateCompanyOverrideRequestBodyMetricPeriod.Raw | null;
        metric_period_month_reset?: UpdateCompanyOverrideRequestBodyMetricPeriodMonthReset.Raw | null;
        note?: string | null;
        value_bool?: boolean | null;
        value_credit_id?: string | null;
        value_numeric?: number | null;
        value_trait_id?: string | null;
        value_type: EntitlementValueType.Raw;
    }
}
