// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../index.js";

/**
 * @example
 *     {
 *         add_on_ids: ["add_on_ids"],
 *         checkout_collect_address: true,
 *         checkout_collect_email: true,
 *         checkout_collect_phone: true,
 *         enable_tax_collection: true,
 *         ordered_add_ons: [{
 *                 plan_id: "plan_id"
 *             }],
 *         ordered_bundle_list: [{
 *                 bundleId: "bundleId"
 *             }],
 *         ordered_plans: [{
 *                 plan_id: "plan_id"
 *             }],
 *         prevent_downgrades_when_over_limit: true,
 *         show_credits: true,
 *         show_period_toggle: true,
 *         show_zero_price_as_free: true,
 *         sync_customer_billing_details_for_tax: true
 *     }
 */
export interface CreatePlanGroupRequestBody {
    add_on_compatibilities?: Schematic.CompatiblePlans[];
    /** Use OrderedAddOns instead */
    add_on_ids: string[];
    checkout_collect_address: boolean;
    checkout_collect_email: boolean;
    checkout_collect_phone: boolean;
    custom_plan_config?: Schematic.CustomPlanConfig;
    custom_plan_id?: string;
    default_plan_id?: string;
    enable_tax_collection: boolean;
    fallback_plan_id?: string;
    initial_plan_id?: string;
    initial_plan_price_id?: string;
    ordered_add_ons: Schematic.OrderedPlansInGroup[];
    ordered_bundle_list: Schematic.PlanGroupBundleOrder[];
    ordered_plans: Schematic.OrderedPlansInGroup[];
    prevent_downgrades_when_over_limit: boolean;
    show_credits: boolean;
    show_period_toggle: boolean;
    show_zero_price_as_free: boolean;
    sync_customer_billing_details_for_tax: boolean;
    trial_days?: number;
    trial_expiry_plan_id?: string;
    trial_expiry_plan_price_id?: string;
    trial_payment_method_required?: boolean;
}
