// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const GetPlanParams: core.serialization.ObjectSchema<serializers.GetPlanParams.Raw, Schematic.GetPlanParams> =
    core.serialization.object({
        planVersionId: core.serialization.property("plan_version_id", core.serialization.string().optional()),
    });

export declare namespace GetPlanParams {
    export interface Raw {
        plan_version_id?: string | null;
    }
}
