/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Schematic from "../../../../api/index";
import * as core from "../../../../core";

export const UpsertBillingProductRequestBodyChargeType: core.serialization.Schema<
    serializers.UpsertBillingProductRequestBodyChargeType.Raw,
    Schematic.UpsertBillingProductRequestBodyChargeType
> = core.serialization.enum_(["one_time", "recurring", "free"]);

export declare namespace UpsertBillingProductRequestBodyChargeType {
    export type Raw = "one_time" | "recurring" | "free";
}
