// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         companyIds: ["company_ids"],
 *         planId: "plan_id",
 *         planVersionIdTo: "plan_version_id_to",
 *         targetPlanType: "plan"
 *     }
 */
export interface PreviewMigrationRequestBody {
    companyIds: string[];
    planId: string;
    planVersionIdTo: string;
    targetPlanType: Schematic.PlanType;
}
