// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index.js";

export interface ListCrmProductsResponse {
    data: Schematic.CrmProductResponseData[];
    /** Input parameters */
    params: ListCrmProductsResponse.Params;
}

export namespace ListCrmProductsResponse {
    /**
     * Input parameters
     */
    export interface Params {
        ids?: string[];
        /** Page limit (default 100) */
        limit?: number;
        name?: string;
        /** Page offset (default 0) */
        offset?: number;
    }
}
