/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../index";

export interface UpsertCrmDealResponse {
  data: Schematic.CrmDealResponseData;
  /** Input parameters */
  params: Record<string, unknown>;
}
