// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         amount_off: 1,
 *         duration: "duration",
 *         duration_in_months: 1,
 *         external_id: "external_id",
 *         max_redemptions: 1,
 *         name: "name",
 *         percent_off: 1.1,
 *         times_redeemed: 1
 *     }
 */
export interface CreateCouponRequestBody {
    amount_off: number;
    currency?: string;
    duration: string;
    duration_in_months: number;
    external_id: string;
    max_redemptions: number;
    name: string;
    percent_off: number;
    times_redeemed: number;
}
