/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         billingScheme: "per_unit",
 *         currency: "currency",
 *         externalAccountId: "external_account_id",
 *         interval: "interval",
 *         isActive: true,
 *         price: 1,
 *         priceExternalId: "price_external_id",
 *         priceTiers: [{
 *                 priceExternalId: "price_external_id"
 *             }],
 *         productExternalId: "product_external_id",
 *         usageType: "licensed"
 *     }
 */
export interface CreateBillingPriceRequestBody {
    billingScheme: Schematic.CreateBillingPriceRequestBodyBillingScheme;
    currency: string;
    externalAccountId: string;
    interval: string;
    isActive: boolean;
    meterId?: string;
    packageSize?: number;
    price: number;
    priceDecimal?: string;
    priceExternalId: string;
    priceTiers: Schematic.CreateBillingPriceTierRequestBody[];
    productExternalId: string;
    tierMode?: Schematic.CreateBillingPriceRequestBodyTierMode;
    usageType: Schematic.CreateBillingPriceRequestBodyUsageType;
}
