/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import { RawEventBatchResponseData } from "../../../types/RawEventBatchResponseData";

export const CreateEventBatchResponse: core.serialization.ObjectSchema<
  serializers.CreateEventBatchResponse.Raw,
  Schematic.CreateEventBatchResponse
> = core.serialization.object({
  data: RawEventBatchResponseData,
  params: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace CreateEventBatchResponse {
  interface Raw {
    data: RawEventBatchResponseData.Raw;
    params: Record<string, unknown>;
  }
}
