// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";

export const ReserveCreditsRequestBody: core.serialization.Schema<
    serializers.ReserveCreditsRequestBody.Raw,
    Schematic.ReserveCreditsRequestBody
> = core.serialization.object({
    amount: core.serialization.number(),
    companyId: core.serialization.property("company_id", core.serialization.string()),
    creditTypeId: core.serialization.property("credit_type_id", core.serialization.string()),
    expiresAt: core.serialization.property("expires_at", core.serialization.date().optional()),
    idempotencyKey: core.serialization.property("idempotency_key", core.serialization.string().optional()),
});

export declare namespace ReserveCreditsRequestBody {
    export interface Raw {
        amount: number;
        company_id: string;
        credit_type_id: string;
        expires_at?: string | null;
        idempotency_key?: string | null;
    }
}
