// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";

export const UpdateCreditSpendPolicyRequestBody: core.serialization.Schema<
    serializers.UpdateCreditSpendPolicyRequestBody.Raw,
    Schematic.UpdateCreditSpendPolicyRequestBody
> = core.serialization.object({
    label: core.serialization.string().optional(),
    maxPerDraw: core.serialization.property("max_per_draw", core.serialization.number().optional()),
});

export declare namespace UpdateCreditSpendPolicyRequestBody {
    export interface Raw {
        label?: string | null;
        max_per_draw?: number | null;
    }
}
