// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { CountResponse } from "../../../types/CountResponse";
import { CountCompaniesForAdvancedFilterParams } from "./CountCompaniesForAdvancedFilterParams";

export const CountCompaniesForAdvancedFilterResponse: core.serialization.ObjectSchema<
    serializers.CountCompaniesForAdvancedFilterResponse.Raw,
    Schematic.CountCompaniesForAdvancedFilterResponse
> = core.serialization.object({
    data: CountResponse,
    params: CountCompaniesForAdvancedFilterParams,
});

export declare namespace CountCompaniesForAdvancedFilterResponse {
    export interface Raw {
        data: CountResponse.Raw;
        params: CountCompaniesForAdvancedFilterParams.Raw;
    }
}
