// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { CountResponse } from "../../../types/CountResponse";
import { CountEntityTraitsParams } from "./CountEntityTraitsParams";

export const CountEntityTraitsResponse: core.serialization.ObjectSchema<
    serializers.CountEntityTraitsResponse.Raw,
    Schematic.CountEntityTraitsResponse
> = core.serialization.object({
    data: CountResponse,
    params: CountEntityTraitsParams,
});

export declare namespace CountEntityTraitsResponse {
    export interface Raw {
        data: CountResponse.Raw;
        params: CountEntityTraitsParams.Raw;
    }
}
