// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { DeleteResponse } from "../../../types/DeleteResponse";
import { DeleteCompanyParams } from "./DeleteCompanyParams";

export const DeleteCompanyResponse: core.serialization.ObjectSchema<
    serializers.DeleteCompanyResponse.Raw,
    Schematic.DeleteCompanyResponse
> = core.serialization.object({
    data: DeleteResponse,
    params: DeleteCompanyParams,
});

export declare namespace DeleteCompanyResponse {
    export interface Raw {
        data: DeleteResponse.Raw;
        params: DeleteCompanyParams.Raw;
    }
}
