/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import { PlanChangeResponseData } from "../../../types/PlanChangeResponseData";

export const GetPlanChangeResponse: core.serialization.ObjectSchema<
    serializers.GetPlanChangeResponse.Raw,
    Schematic.GetPlanChangeResponse
> = core.serialization.object({
    data: PlanChangeResponseData,
    params: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace GetPlanChangeResponse {
    export interface Raw {
        data: PlanChangeResponseData.Raw;
        params: Record<string, unknown>;
    }
}
