/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import { EntityKeyDefinitionResponseData } from "../../../types/EntityKeyDefinitionResponseData";
import { ListEntityKeyDefinitionsParams } from "./ListEntityKeyDefinitionsParams";

export const ListEntityKeyDefinitionsResponse: core.serialization.ObjectSchema<
    serializers.ListEntityKeyDefinitionsResponse.Raw,
    Schematic.ListEntityKeyDefinitionsResponse
> = core.serialization.object({
    data: core.serialization.list(EntityKeyDefinitionResponseData),
    params: ListEntityKeyDefinitionsParams,
});

export declare namespace ListEntityKeyDefinitionsResponse {
    interface Raw {
        data: EntityKeyDefinitionResponseData.Raw[];
        params: ListEntityKeyDefinitionsParams.Raw;
    }
}
