// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index.js";

export interface CountEntityTraitDefinitionsResponse {
    data: Schematic.CountResponse;
    /** Input parameters */
    params: CountEntityTraitDefinitionsResponse.Params;
}

export namespace CountEntityTraitDefinitionsResponse {
    /**
     * Input parameters
     */
    export interface Params {
        entity_type?: Schematic.EntityType;
        ids?: string[];
        /** Page limit (default 100) */
        limit?: number;
        /** Page offset (default 0) */
        offset?: number;
        q?: string;
        trait_type?: Schematic.TraitType;
        trait_types?: Schematic.TraitType[];
    }
}
