// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index.js";

export interface CountUsersResponse {
    data: Schematic.CountResponse;
    /** Input parameters */
    params: CountUsersResponse.Params;
}

export namespace CountUsersResponse {
    /**
     * Input parameters
     */
    export interface Params {
        /** Filter users by company ID (starts with comp_) */
        company_id?: string;
        /** Filter users by multiple user IDs (starts with user_) */
        ids?: string[];
        /** Page limit (default 100) */
        limit?: number;
        /** Page offset (default 0) */
        offset?: number;
        /** Filter users by plan ID (starts with plan_) */
        plan_id?: string;
        /** Search for users by name, keys or string traits */
        q?: string;
    }
}
