/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../index";

export interface GetActiveCompanySubscriptionResponse {
    data: Schematic.CompanySubscriptionResponseData[];
    /** Input parameters */
    params: Schematic.GetActiveCompanySubscriptionParams;
}
