/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../index.js";

export interface ListEntityKeyDefinitionsResponse {
    /** The returned resources */
    data: Schematic.EntityKeyDefinitionResponseData[];
    /** Input parameters */
    params: ListEntityKeyDefinitionsResponse.Params;
}

export namespace ListEntityKeyDefinitionsResponse {
    /**
     * Input parameters
     */
    export interface Params {
        entity_type?: Params.EntityType;
        ids?: string[];
        /** Page limit (default 100) */
        limit?: number;
        /** Page offset (default 0) */
        offset?: number;
        q?: string;
    }

    export namespace Params {
        export type EntityType = "company" | "user";
        export const EntityType = {
            Company: "company",
            User: "user",
        } as const;
    }
}
