// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index.js";

export interface ListEntityKeyDefinitionsResponse {
    data: Schematic.EntityKeyDefinitionResponseData[];
    /** Input parameters */
    params: ListEntityKeyDefinitionsResponse.Params;
}

export namespace ListEntityKeyDefinitionsResponse {
    /**
     * Input parameters
     */
    export interface Params {
        entity_type?: Schematic.EntityType;
        ids?: string[];
        /** Page limit (default 100) */
        limit?: number;
        /** Page offset (default 0) */
        offset?: number;
        q?: string;
    }
}
