/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ListEntityTraitDefinitionsRequestEntityType = "company" | "user";
export const ListEntityTraitDefinitionsRequestEntityType = {
    Company: "company",
    User: "user",
} as const;
