/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ListEntityKeyDefinitionsRequestEntityType = "company" | "user";

export const ListEntityKeyDefinitionsRequestEntityType = {
    Company: "company",
    User: "user",
} as const;
