// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { FeatureUsageTimeSeriesResponseData } from "../../../types/FeatureUsageTimeSeriesResponseData";
import { GetFeatureUsageTimeSeriesParams } from "./GetFeatureUsageTimeSeriesParams";

export const GetFeatureUsageTimeSeriesResponse: core.serialization.ObjectSchema<
    serializers.GetFeatureUsageTimeSeriesResponse.Raw,
    Schematic.GetFeatureUsageTimeSeriesResponse
> = core.serialization.object({
    data: FeatureUsageTimeSeriesResponseData,
    params: GetFeatureUsageTimeSeriesParams,
});

export declare namespace GetFeatureUsageTimeSeriesResponse {
    export interface Raw {
        data: FeatureUsageTimeSeriesResponseData.Raw;
        params: GetFeatureUsageTimeSeriesParams.Raw;
    }
}
