// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { FeatureCompanyUserResponseData } from "../../../types/FeatureCompanyUserResponseData";
import { ListFeatureUsersParams } from "./ListFeatureUsersParams";

export const ListFeatureUsersResponse: core.serialization.ObjectSchema<
    serializers.ListFeatureUsersResponse.Raw,
    Schematic.ListFeatureUsersResponse
> = core.serialization.object({
    data: core.serialization.list(FeatureCompanyUserResponseData),
    params: ListFeatureUsersParams,
});

export declare namespace ListFeatureUsersResponse {
    export interface Raw {
        data: FeatureCompanyUserResponseData.Raw[];
        params: ListFeatureUsersParams.Raw;
    }
}
