/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Schematic from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCompanyOverrideRequestBodyMetricPeriodMonthReset: core.serialization.Schema<
    serializers.UpdateCompanyOverrideRequestBodyMetricPeriodMonthReset.Raw,
    Schematic.UpdateCompanyOverrideRequestBodyMetricPeriodMonthReset
> = core.serialization.enum_(["first_of_month", "billing_cycle"]);

export declare namespace UpdateCompanyOverrideRequestBodyMetricPeriodMonthReset {
    export type Raw = "first_of_month" | "billing_cycle";
}
