/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         environment_type: "development",
 *         name: "name"
 *     }
 */
export interface CreateEnvironmentRequestBody {
    environment_type: CreateEnvironmentRequestBody.EnvironmentType;
    name: string;
}

export namespace CreateEnvironmentRequestBody {
    export type EnvironmentType = "development" | "staging" | "production";
    export const EnvironmentType = {
        Development: "development",
        Staging: "staging",
        Production: "production",
    } as const;
}
