// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../index";

/**
 * @example
 *     {}
 */
export interface UpdateOnboardingStateRequestBody {
    country?: string;
    dismissed?: boolean;
    path?: Schematic.OnboardingPath;
    pricingPageUrl?: string;
    track?: Schematic.OnboardingTrack;
    websiteUrl?: string;
}
