// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { DataExportResponseData } from "../../../types/DataExportResponseData";

export const CreateDataExportResponse: core.serialization.ObjectSchema<
    serializers.CreateDataExportResponse.Raw,
    Schematic.CreateDataExportResponse
> = core.serialization.object({
    data: DataExportResponseData,
    params: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace CreateDataExportResponse {
    export interface Raw {
        data: DataExportResponseData.Raw;
        params: Record<string, unknown>;
    }
}
