// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index.js";

export interface CountWebhookEventsResponse {
    data: Schematic.CountResponse;
    /** Input parameters */
    params: CountWebhookEventsResponse.Params;
}

export namespace CountWebhookEventsResponse {
    /**
     * Input parameters
     */
    export interface Params {
        ids?: string[];
        /** Page limit (default 100) */
        limit?: number;
        /** Page offset (default 0) */
        offset?: number;
        q?: string;
        webhook_id?: string;
    }
}
