// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index.js";

export interface UpdateWebhookResponse {
    data: Schematic.WebhookResponseData;
    /** Input parameters */
    params: Record<string, unknown>;
}
