// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../index.js";

/**
 * @example
 *     {
 *         description: "description",
 *         name: "name",
 *         plan_type: "plan"
 *     }
 */
export interface CreatePlanRequestBody {
    description: string;
    icon?: string;
    name: string;
    plan_type: Schematic.PlanType;
}
