// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         companyId: "company_id",
 *         description: "description",
 *         name: "name"
 *     }
 */
export interface CreateCustomPlanRequestBody {
    companyId: string;
    copiedFromPlanId?: string;
    description: string;
    icon?: Schematic.PlanIcon;
    name: string;
}
