/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         plan_id: "plan_id",
 *         trait_id: "trait_id",
 *         trait_value: "trait_value"
 *     }
 */
export interface CreatePlanTraitRequestBody {
    plan_id: string;
    trait_id: string;
    trait_value: string;
}
