/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         entityType: "company",
 *         hierarchy: ["hierarchy"],
 *         traitType: "boolean"
 *     }
 */
export interface CreateEntityTraitDefinitionRequestBody {
    displayName?: string;
    entityType: Schematic.CreateEntityTraitDefinitionRequestBodyEntityType;
    hierarchy: string[];
    traitType: Schematic.CreateEntityTraitDefinitionRequestBodyTraitType;
}
