/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListUsersRequest {
    /**
     * Filter users by company ID (starts with comp\_)
     */
    companyId?: string;
    /**
     * Filter users by multiple user IDs (starts with user\_)
     */
    ids?: string | string[];
    /**
     * Filter users by plan ID (starts with plan\_)
     */
    planId?: string;
    /**
     * Search for users by name, keys or string traits
     */
    q?: string;
    /**
     * Page limit (default 100)
     */
    limit?: number;
    /**
     * Page offset (default 0)
     */
    offset?: number;
}
