/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../index.js";

export interface UpdatePlanGroupResponse {
    data: Schematic.PlanGroupResponseData;
    /** Input parameters */
    params: Record<string, unknown>;
}
