// This file was auto-generated by Fern from our API Definition.

export const ApiKeyScope = {
    Admin: "admin",
    Capture: "capture",
    Read: "read",
    Write: "write",
} as const;
export type ApiKeyScope = (typeof ApiKeyScope)[keyof typeof ApiKeyScope];
