// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index";

export interface ApiKeyIntegrationResponseData {
    id: string;
    state: Schematic.IntegrationState;
    type: Schematic.IntegrationType;
}
