// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index.js";

export interface AudienceRequestBody {
    condition_groups: Schematic.CreateOrUpdateConditionGroupRequestBody[];
    conditions: Schematic.CreateOrUpdateConditionRequestBody[];
    /** Page limit (default 100) */
    limit?: number;
    /** Page offset (default 0) */
    offset?: number;
    q?: string;
}
