/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BillingCreditExpiryType =
    | "duration"
    | "end_of_billing_period"
    | "end_of_next_billing_period"
    | "end_of_trial"
    | "no_expiry";
export const BillingCreditExpiryType = {
    Duration: "duration",
    EndOfBillingPeriod: "end_of_billing_period",
    EndOfNextBillingPeriod: "end_of_next_billing_period",
    EndOfTrial: "end_of_trial",
    NoExpiry: "no_expiry",
} as const;
