/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BillingPriceResponseData {
    externalPriceId: string;
    id: string;
    interval: string;
    price: number;
}
