// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index.js";

export interface BillingProductPriceResponseData {
    billing_scheme: Schematic.BillingPriceScheme;
    created_at: string;
    currency: string;
    id: string;
    interval: Schematic.BillingProductPriceInterval;
    is_active: boolean;
    meter_id?: string;
    package_size: number;
    price: number;
    price_decimal?: string;
    price_external_id: string;
    product_external_id: string;
    tiers_mode?: Schematic.BillingTiersMode;
    updated_at: string;
    usage_type: Schematic.BillingPriceUsageType;
}
