/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../index";

/**
 * The requested resource
 */
export interface CheckoutDataResponseData {
    activeAddOns: Schematic.PlanDetailResponseData[];
    activePlan?: Schematic.PlanDetailResponseData;
    activeUsageBasedEntitlements: Schematic.UsageBasedEntitlementResponseData[];
    company?: Schematic.CompanyDetailResponseData;
    featureUsage?: Schematic.FeatureUsageDetailResponseData;
    selectedPlan?: Schematic.PlanDetailResponseData;
    selectedUsageBasedEntitlements: Schematic.UsageBasedEntitlementResponseData[];
    subscription?: Schematic.CompanySubscriptionResponseData;
}
