/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CompanyPlanDetailResponseDataInvalidReason = "feature_usage_exceeded" | "downgrade_not_permitted";
export const CompanyPlanDetailResponseDataInvalidReason = {
    FeatureUsageExceeded: "feature_usage_exceeded",
    DowngradeNotPermitted: "downgrade_not_permitted",
} as const;
