// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index";

export interface CompanyBillingDetailsResponseData {
    address?: Schematic.CompanyBillingAddressView;
    checkoutSettings: Schematic.CompanyBillingCheckoutSettings;
    customFields: Schematic.CheckoutFieldWithValue[];
    email?: string;
    phone?: string;
}
