// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index";

export interface CompanyBillingProfileResponseData {
    accountId: string;
    billingCustomerId?: string;
    collectionMethod: Schematic.BillingCollectionMethod;
    companyId: string;
    createdAt: Date;
    daysUntilDue?: number;
    environmentId: string;
    id: string;
    isDefault: boolean;
    name?: string;
    paymentMethodId?: string;
    prorationBehavior?: Schematic.ProrationBehavior;
    providerType: Schematic.BillingProviderType;
    updatedAt: Date;
}
