/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../index";

export interface CompanyCrmDealsResponseData {
    dealArr: string;
    dealExternalId: string;
    dealMrr: string;
    dealName?: string;
    lineItems: Schematic.CrmDealLineItem[];
}
