/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../index";

export interface CreateReqCommon {
  featureId: string;
  metricPeriod?: Schematic.CreateReqCommonMetricPeriod;
  valueBool?: boolean;
  valueNumeric?: number;
  valueTraitId?: string;
  valueType: Schematic.CreateReqCommonValueType;
}
