// This file was auto-generated by Fern from our API Definition.

export const CreateEntitlementReqCommonMetricPeriod = {
    AllTime: "all_time",
    CurrentMonth: "current_month",
    CurrentWeek: "current_week",
    CurrentDay: "current_day",
} as const;
export type CreateEntitlementReqCommonMetricPeriod =
    (typeof CreateEntitlementReqCommonMetricPeriod)[keyof typeof CreateEntitlementReqCommonMetricPeriod];
