// This file was auto-generated by Fern from our API Definition.

export const CreditEventType = {
    Grant: "grant",
    Transfer: "transfer",
    Usage: "usage",
    ZeroOut: "zero_out",
} as const;
export type CreditEventType = (typeof CreditEventType)[keyof typeof CreditEventType];
