// This file was auto-generated by Fern from our API Definition.

export const CreditLedgerEntryKind = {
    Adjustment: "adjustment",
    Charge: "charge",
    Drawdown: "drawdown",
    Grant: "grant",
    Settlement: "settlement",
    Transfer: "transfer",
    ZeroOut: "zero_out",
} as const;
export type CreditLedgerEntryKind = (typeof CreditLedgerEntryKind)[keyof typeof CreditLedgerEntryKind];
