// This file was auto-generated by Fern from our API Definition.

export const CreditUsageReason = {
    LeaseHold: "lease_hold",
    LeaseRelease: "lease_release",
    ManualAdjustment: "manual_adjustment",
    Reconciliation: "reconciliation",
    ReservationHold: "reservation_hold",
    ReservationRelease: "reservation_release",
    Track: "track",
} as const;
export type CreditUsageReason = (typeof CreditUsageReason)[keyof typeof CreditUsageReason];
