// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index";

export interface DatastreamCompanyPlan {
    id: string;
    name: string;
    trialEndDate?: Date;
    trialStatus?: Schematic.TrialStatus;
}
