// This file was auto-generated by Fern from our API Definition.

export interface FeatureUsageHistoryResponseData {
    /** Companies are identified by ID only. To report against your own identifiers, resolve them once via the companies API and cache the mapping; keys are not repeated on every row. */
    companyId: string;
    eventSubtype: string;
    featureId: string;
    /** Exclusive end of the period this usage covers */
    periodEnd: Date;
    /** Inclusive start of the period this usage covers */
    periodStart: Date;
    /** Usage recorded within this period; an incremental total, not a running one */
    usage: number;
}
