/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FeatureUsageDataResponseData {
    entitlement_source: string;
    entitlement_value_type: string;
    feature_id: string;
    feature_name: string;
    feature_type: string;
    hard_limit: string;
    has_access: boolean;
    soft_limit: string;
    usage: string;
}
