/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of allocation that is being used.
 */
export type FeatureUsageResponseDataAllocationType = "boolean" | "numeric" | "trait" | "unlimited";

export const FeatureUsageResponseDataAllocationType = {
  Boolean: "boolean",
  Numeric: "numeric",
  Trait: "trait",
  Unlimited: "unlimited",
} as const;
