// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index";

export interface PlanVersionResponseData {
    createdAt: Date;
    description: string;
    environmentId: string;
    icon: string;
    id: string;
    name: string;
    originalPlanId?: string;
    planType: Schematic.PlanType;
    status: Schematic.PlanVersionStatus;
    updatedAt: Date;
    version: number;
}
