// This file was auto-generated by Fern from our API Definition.

export const PlanVersionCompanyMigrationStatus = {
    Completed: "completed",
    Failed: "failed",
    InProgress: "in_progress",
    Pending: "pending",
    Skipped: "skipped",
} as const;
export type PlanVersionCompanyMigrationStatus =
    (typeof PlanVersionCompanyMigrationStatus)[keyof typeof PlanVersionCompanyMigrationStatus];
