// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index";

export interface PlanVersionCompanyMigrationResponseData {
    companyId: string;
    companyName: string;
    completedAt?: Date;
    createdAt: Date;
    error?: string;
    id: string;
    migrationId: string;
    planVersionIdFrom?: string;
    startedAt?: Date;
    status: Schematic.PlanVersionCompanyMigrationStatus;
    updatedAt: Date;
}
