// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index";

export interface PlanGroupResponseData {
    addOnCompatibilities: Schematic.CompatiblePlansResponseData[];
    addOnIds: string[];
    checkoutSettings: Schematic.CheckoutSettingsResponseData;
    componentSettings: Schematic.ComponentSettingsResponseData;
    defaultPlanId?: string;
    fallbackPlanId?: string;
    id: string;
    initialPlanId?: string;
    initialPlanPriceId?: string;
    orderedAddOnIds: Schematic.OrderedPlansInGroup[];
    planIds: Schematic.OrderedPlansInGroup[];
    preventDowngradesWhenOverLimit: boolean;
    preventSelfServiceDowngrade: boolean;
    preventSelfServiceDowngradeButtonText?: string;
    preventSelfServiceDowngradeUrl?: string;
    prorationBehavior: string;
    showAsMonthlyPrices: boolean;
    showCredits: boolean;
    showPeriodToggle: boolean;
    showZeroPriceAsFree: boolean;
    syncCustomerBillingDetails: boolean;
    taxCollectionEnabled: boolean;
    trialDays?: number;
    trialExpiryPlanId?: string;
    trialExpiryPlanPriceId?: string;
    trialPaymentMethodRequired?: boolean;
}
