// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index";

export interface PreviewSubscriptionFinanceResponseData {
    amountOff: number;
    dueNow: number;
    newCharges: number;
    percentOff: number;
    periodStart: Date;
    promoCodeApplied: boolean;
    proration: number;
    taxAmount?: number;
    taxDisplayName?: string;
    taxRequireBillingDetails: boolean;
    totalPerBillingPeriod: number;
    trialEnd?: Date;
    upcomingInvoiceLineItems: Schematic.PreviewSubscriptionUpcomingInvoiceLineItems[];
}
