// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../index";

export interface RuleConditionResponseData {
    comparisonTraitId?: string;
    conditionGroupId?: string;
    conditionType: Schematic.ConditionType;
    createdAt: Date;
    environmentId: string;
    eventSubtype?: string;
    flagId?: string;
    id: string;
    metricPeriod?: Schematic.MetricPeriod;
    metricPeriodMonthReset?: Schematic.MetricPeriodMonthReset;
    metricValue?: number;
    operator: Schematic.ComparableOperator;
    resourceIds: string[];
    ruleId: string;
    traitEntityType?: Schematic.EntityType;
    traitId?: string;
    traitValue: string;
    updatedAt: Date;
}
