// This file was auto-generated by Fern from our API Definition.

export const RulesengineConditionMetricPeriodMonthReset = {
    FirstOfMonth: "first_of_month",
    BillingCycle: "billing_cycle",
} as const;
export type RulesengineConditionMetricPeriodMonthReset =
    (typeof RulesengineConditionMetricPeriodMonthReset)[keyof typeof RulesengineConditionMetricPeriodMonthReset];
