// This file was auto-generated by Fern from our API Definition.

/** The current schema version hash for rules engine types. The first enum value is always the current version. */
export const RulesEngineSchemaVersion = {
    Vf05Bf5Da: "vf05bf5da",
    PlaceholderForFernCompatibility: "placeholder-for-fern-compatibility",
} as const;
export type RulesEngineSchemaVersion = (typeof RulesEngineSchemaVersion)[keyof typeof RulesEngineSchemaVersion];
