// This file was auto-generated by Fern from our API Definition.

export const RulesengineRuleRuleType = {
    Default: "default",
    GlobalOverride: "global_override",
    CompanyOverride: "company_override",
    CompanyOverrideUsageExceeded: "company_override_usage_exceeded",
    PlanEntitlement: "plan_entitlement",
    PlanEntitlementUsageExceeded: "plan_entitlement_usage_exceeded",
    Standard: "standard",
} as const;
export type RulesengineRuleRuleType = (typeof RulesengineRuleRuleType)[keyof typeof RulesengineRuleRuleType];
