// This file was auto-generated by Fern from our API Definition.

export interface ScheduledDowngradeResponseData {
    currency: string;
    effectiveAfter: Date;
    fromPlanId: string;
    fromPlanName: string;
    fromSubscriptionPrice: number;
    id: string;
    interval: string;
    scheduledInterval?: string;
    scheduledPrice?: number;
    toPlanId: string;
    toPlanName: string;
}
