/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StripeEmbedInfo {
    account_id?: string;
    publishable_key?: string;
    schematic_publishable_key: string;
    setup_intent_client_secret?: string;
}
