/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateReqCommonValueType = "boolean" | "numeric" | "trait" | "unlimited";

export const UpdateReqCommonValueType = {
  Boolean: "boolean",
  Numeric: "numeric",
  Trait: "trait",
  Unlimited: "unlimited",
} as const;
