/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpsertCompanyRequestBody {
    /** If you know the Schematic ID, you can use that here instead of keys */
    id?: string;
    /** See [Key Management](https://docs.schematichq.com/developer_resources/key_management) for more information */
    keys: Record<string, string>;
    lastSeenAt?: Date;
    name?: string;
    /** A map of trait names to trait values */
    traits?: Record<string, unknown>;
    updateOnly?: boolean;
}
