// This file was auto-generated by Fern from our API Definition.

export interface UserDailyCreditPointResponseData {
    /** The user's net credit consumption on the day */
    creditsUsed: number;
    /** The UTC day */
    date: Date;
}
