/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Schematic from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCreditBundleRequestBodyExpiryUnit: core.serialization.Schema<
    serializers.CreateCreditBundleRequestBodyExpiryUnit.Raw,
    Schematic.CreateCreditBundleRequestBodyExpiryUnit
> = core.serialization.enum_(["days", "billing_periods"]);

export declare namespace CreateCreditBundleRequestBodyExpiryUnit {
    export type Raw = "days" | "billing_periods";
}
