// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { DeleteResponse } from "../../../types/DeleteResponse";

export const DeleteCreditBundleResponse: core.serialization.ObjectSchema<
    serializers.DeleteCreditBundleResponse.Raw,
    Schematic.DeleteCreditBundleResponse
> = core.serialization.object({
    data: DeleteResponse,
    params: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace DeleteCreditBundleResponse {
    export interface Raw {
        data: DeleteResponse.Raw;
        params: Record<string, unknown>;
    }
}
