// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { CreditLeaseResponseData } from "../../../types/CreditLeaseResponseData";

export const ExtendCreditLeaseResponse: core.serialization.ObjectSchema<
    serializers.ExtendCreditLeaseResponse.Raw,
    Schematic.ExtendCreditLeaseResponse
> = core.serialization.object({
    data: CreditLeaseResponseData,
    params: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace ExtendCreditLeaseResponse {
    export interface Raw {
        data: CreditLeaseResponseData.Raw;
        params: Record<string, unknown>;
    }
}
