// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const GetCreditSpendPolicyUsageParams: core.serialization.ObjectSchema<
    serializers.GetCreditSpendPolicyUsageParams.Raw,
    Schematic.GetCreditSpendPolicyUsageParams
> = core.serialization.object({
    billingCreditId: core.serialization.property("billing_credit_id", core.serialization.string().optional()),
    companyId: core.serialization.property("company_id", core.serialization.string().optional()),
    userIds: core.serialization.property("user_ids", core.serialization.list(core.serialization.string()).optional()),
});

export declare namespace GetCreditSpendPolicyUsageParams {
    export interface Raw {
        billing_credit_id?: string | null;
        company_id?: string | null;
        user_ids?: string[] | null;
    }
}
