// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { CreditEventType } from "../../../types/CreditEventType";

export const ListCreditEventLedgerParams: core.serialization.ObjectSchema<
    serializers.ListCreditEventLedgerParams.Raw,
    Schematic.ListCreditEventLedgerParams
> = core.serialization.object({
    billingCreditId: core.serialization.property("billing_credit_id", core.serialization.string().optional()),
    companyId: core.serialization.property("company_id", core.serialization.string().optional()),
    endTime: core.serialization.property("end_time", core.serialization.string().optional()),
    eventType: core.serialization.property("event_type", CreditEventType.optional()),
    featureId: core.serialization.property("feature_id", core.serialization.string().optional()),
    limit: core.serialization.number().optional(),
    offset: core.serialization.number().optional(),
    startTime: core.serialization.property("start_time", core.serialization.string().optional()),
});

export declare namespace ListCreditEventLedgerParams {
    export interface Raw {
        billing_credit_id?: string | null;
        company_id?: string | null;
        end_time?: string | null;
        event_type?: CreditEventType.Raw | null;
        feature_id?: string | null;
        limit?: number | null;
        offset?: number | null;
        start_time?: string | null;
    }
}
