// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         company_id: "company_id"
 *     }
 */
export interface CancelSubscriptionRequest {
    /** If false, subscription cancels at period end. Defaults to true. */
    cancel_immediately?: boolean;
    company_id: string;
    /** If true and cancel_immediately is true, issue prorated credit. Defaults to true. */
    prorate?: boolean;
}
