// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         integrationId: "integration_id"
 *     }
 */
export interface StartDataImportRequestBody {
    companyMatchingCriteria?: Schematic.CompanyMatchingCriteria;
    companyMatchingField?: string;
    integrationId: string;
}
