// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { WebhookResponseData } from "../../../types/WebhookResponseData";

export const CreateWebhookResponse: core.serialization.ObjectSchema<
    serializers.CreateWebhookResponse.Raw,
    Schematic.CreateWebhookResponse
> = core.serialization.object({
    data: WebhookResponseData,
    params: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace CreateWebhookResponse {
    export interface Raw {
        data: WebhookResponseData.Raw;
        params: Record<string, unknown>;
    }
}
