// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         exportType: "audit-log",
 *         status: "failure",
 *         limit: 1000000,
 *         offset: 1000000
 *     }
 */
export interface ListDataExportsRequest {
    exportType?: Schematic.DataExportType;
    status?: Schematic.DataExportStatus;
    /** Page limit (default 100) */
    limit?: number;
    /** Page offset (default 0) */
    offset?: number;
}
