/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../index.js";

export interface CreateEnvironmentResponse {
    data: Schematic.EnvironmentDetailResponseData;
    /** Input parameters */
    params: Record<string, unknown>;
}
