/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import { BillingProductDetailResponseData } from "../../../types/BillingProductDetailResponseData";
import { ListBillingProductsParams } from "./ListBillingProductsParams";

export const ListBillingProductsResponse: core.serialization.ObjectSchema<
  serializers.ListBillingProductsResponse.Raw,
  Schematic.ListBillingProductsResponse
> = core.serialization.object({
  data: core.serialization.list(BillingProductDetailResponseData),
  params: ListBillingProductsParams,
});

export declare namespace ListBillingProductsResponse {
  interface Raw {
    data: BillingProductDetailResponseData.Raw[];
    params: ListBillingProductsParams.Raw;
  }
}
