/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Schematic from "../../../../api/index";
import * as core from "../../../../core";

export const SearchBillingPricesRequestUsageType: core.serialization.Schema<
    serializers.SearchBillingPricesRequestUsageType.Raw,
    Schematic.SearchBillingPricesRequestUsageType
> = core.serialization.enum_(["licensed", "metered"]);

export declare namespace SearchBillingPricesRequestUsageType {
    export type Raw = "licensed" | "metered";
}
