// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { IntegrationState } from "./IntegrationState";
import { IntegrationType } from "./IntegrationType";

export const ApiKeyIntegrationResponseData: core.serialization.ObjectSchema<
    serializers.ApiKeyIntegrationResponseData.Raw,
    Schematic.ApiKeyIntegrationResponseData
> = core.serialization.object({
    id: core.serialization.string(),
    state: IntegrationState,
    type: IntegrationType,
});

export declare namespace ApiKeyIntegrationResponseData {
    export interface Raw {
        id: string;
        state: IntegrationState.Raw;
        type: IntegrationType.Raw;
    }
}
