// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { BillingCreditExpiryType } from "./BillingCreditExpiryType";
import { BillingCreditExpiryUnit } from "./BillingCreditExpiryUnit";
import { BillingPlanCreditGrantResetCadence } from "./BillingPlanCreditGrantResetCadence";
import { BillingPlanCreditGrantResetStart } from "./BillingPlanCreditGrantResetStart";
import { BillingPlanCreditGrantResetType } from "./BillingPlanCreditGrantResetType";

export const BillingPlanCreditGrantResponseData: core.serialization.ObjectSchema<
    serializers.BillingPlanCreditGrantResponseData.Raw,
    Schematic.BillingPlanCreditGrantResponseData
> = core.serialization.object({
    autoTopupAmount: core.serialization.property("auto_topup_amount", core.serialization.number().optional()),
    autoTopupAmountType: core.serialization.property("auto_topup_amount_type", core.serialization.string().optional()),
    autoTopupEnabled: core.serialization.property("auto_topup_enabled", core.serialization.boolean()),
    autoTopupExpiryType: core.serialization.property("auto_topup_expiry_type", BillingCreditExpiryType.optional()),
    autoTopupExpiryUnit: core.serialization.property("auto_topup_expiry_unit", BillingCreditExpiryUnit.optional()),
    autoTopupExpiryUnitCount: core.serialization.property(
        "auto_topup_expiry_unit_count",
        core.serialization.number().optional(),
    ),
    autoTopupThresholdPercent: core.serialization.property(
        "auto_topup_threshold_percent",
        core.serialization.number().optional(),
    ),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    creditAmount: core.serialization.property("credit_amount", core.serialization.number()),
    creditId: core.serialization.property("credit_id", core.serialization.string()),
    creditName: core.serialization.property("credit_name", core.serialization.string()),
    creditPluralName: core.serialization.property("credit_plural_name", core.serialization.string().optional()),
    creditSingularName: core.serialization.property("credit_singular_name", core.serialization.string().optional()),
    expiryType: core.serialization.property("expiry_type", BillingCreditExpiryType.optional()),
    expiryUnit: core.serialization.property("expiry_unit", BillingCreditExpiryUnit.optional()),
    expiryUnitCount: core.serialization.property("expiry_unit_count", core.serialization.number().optional()),
    id: core.serialization.string(),
    planId: core.serialization.property("plan_id", core.serialization.string()),
    planName: core.serialization.property("plan_name", core.serialization.string()),
    resetCadence: core.serialization.property("reset_cadence", BillingPlanCreditGrantResetCadence),
    resetStart: core.serialization.property("reset_start", BillingPlanCreditGrantResetStart),
    resetType: core.serialization.property("reset_type", BillingPlanCreditGrantResetType.optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace BillingPlanCreditGrantResponseData {
    export interface Raw {
        auto_topup_amount?: number | null;
        auto_topup_amount_type?: string | null;
        auto_topup_enabled: boolean;
        auto_topup_expiry_type?: BillingCreditExpiryType.Raw | null;
        auto_topup_expiry_unit?: BillingCreditExpiryUnit.Raw | null;
        auto_topup_expiry_unit_count?: number | null;
        auto_topup_threshold_percent?: number | null;
        created_at: string;
        credit_amount: number;
        credit_id: string;
        credit_name: string;
        credit_plural_name?: string | null;
        credit_singular_name?: string | null;
        expiry_type?: BillingCreditExpiryType.Raw | null;
        expiry_unit?: BillingCreditExpiryUnit.Raw | null;
        expiry_unit_count?: number | null;
        id: string;
        plan_id: string;
        plan_name: string;
        reset_cadence: BillingPlanCreditGrantResetCadence.Raw;
        reset_start: BillingPlanCreditGrantResetStart.Raw;
        reset_type?: BillingPlanCreditGrantResetType.Raw | null;
        updated_at: string;
    }
}
