// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const BillingCreditBundleStatus: core.serialization.Schema<
    serializers.BillingCreditBundleStatus.Raw,
    Schematic.BillingCreditBundleStatus
> = core.serialization.enum_(["active", "inactive"]);

export declare namespace BillingCreditBundleStatus {
    export type Raw = "active" | "inactive";
}
