/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Schematic from "../../api/index";
import * as core from "../../core";

export const BillingMeterResponseData: core.serialization.ObjectSchema<
    serializers.BillingMeterResponseData.Raw,
    Schematic.BillingMeterResponseData
> = core.serialization.object({
    dispalyName: core.serialization.property("dispaly_name", core.serialization.string()),
    eventName: core.serialization.property("event_name", core.serialization.string()),
    eventPayloadKey: core.serialization.property("event_payload_key", core.serialization.string()),
    externalPriceId: core.serialization.property("external_price_id", core.serialization.string()),
    id: core.serialization.string(),
});

export declare namespace BillingMeterResponseData {
    export interface Raw {
        dispaly_name: string;
        event_name: string;
        event_payload_key: string;
        external_price_id: string;
        id: string;
    }
}
