/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Schematic from "../../api/index";
import * as core from "../../core";

export const BillingCreditGrantResponseData: core.serialization.ObjectSchema<
    serializers.BillingCreditGrantResponseData.Raw,
    Schematic.BillingCreditGrantResponseData
> = core.serialization.object({
    bundleCurrency: core.serialization.property("bundle_currency", core.serialization.string().optional()),
    bundlePriceDecimal: core.serialization.property("bundle_price_decimal", core.serialization.string().optional()),
    bundlePricePerUnit: core.serialization.property("bundle_price_per_unit", core.serialization.number().optional()),
    companyId: core.serialization.property("company_id", core.serialization.string()),
    companyName: core.serialization.property("company_name", core.serialization.string()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    expiresAt: core.serialization.property("expires_at", core.serialization.date().optional()),
    grantReason: core.serialization.property("grant_reason", core.serialization.string()),
    id: core.serialization.string(),
    planId: core.serialization.property("plan_id", core.serialization.string().optional()),
    planName: core.serialization.property("plan_name", core.serialization.string().optional()),
    quantity: core.serialization.number(),
    quantityRemaining: core.serialization.property("quantity_remaining", core.serialization.number()),
    sourceLabel: core.serialization.property("source_label", core.serialization.string()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    validFrom: core.serialization.property("valid_from", core.serialization.date().optional()),
    zeroedOutDate: core.serialization.property("zeroed_out_date", core.serialization.date().optional()),
    zeroedOutReason: core.serialization.property("zeroed_out_reason", core.serialization.string().optional()),
});

export declare namespace BillingCreditGrantResponseData {
    export interface Raw {
        bundle_currency?: string | null;
        bundle_price_decimal?: string | null;
        bundle_price_per_unit?: number | null;
        company_id: string;
        company_name: string;
        created_at: string;
        expires_at?: string | null;
        grant_reason: string;
        id: string;
        plan_id?: string | null;
        plan_name?: string | null;
        quantity: number;
        quantity_remaining: number;
        source_label: string;
        updated_at: string;
        valid_from?: string | null;
        zeroed_out_date?: string | null;
        zeroed_out_reason?: string | null;
    }
}
