// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CatalogConfigOrderedBundleResponseData } from "./CatalogConfigOrderedBundleResponseData";
import { CatalogConfigOrderedPlanResponseData } from "./CatalogConfigOrderedPlanResponseData";
import { PlanGroupPlanDetailResponseData } from "./PlanGroupPlanDetailResponseData";

export const CatalogConfigurationResponseData: core.serialization.ObjectSchema<
    serializers.CatalogConfigurationResponseData.Raw,
    Schematic.CatalogConfigurationResponseData
> = core.serialization.object({
    addOns: core.serialization.property("add_ons", core.serialization.list(PlanGroupPlanDetailResponseData)),
    customPlanCtaText: core.serialization.property("custom_plan_cta_text", core.serialization.string().optional()),
    customPlanCtaUrl: core.serialization.property("custom_plan_cta_url", core.serialization.string().optional()),
    customPlanPriceText: core.serialization.property("custom_plan_price_text", core.serialization.string().optional()),
    customPlansVisible: core.serialization.property("custom_plans_visible", core.serialization.boolean()),
    orderedAddOns: core.serialization.property(
        "ordered_add_ons",
        core.serialization.list(CatalogConfigOrderedPlanResponseData),
    ),
    orderedBundles: core.serialization.property(
        "ordered_bundles",
        core.serialization.list(CatalogConfigOrderedBundleResponseData),
    ),
    orderedPlans: core.serialization.property(
        "ordered_plans",
        core.serialization.list(CatalogConfigOrderedPlanResponseData),
    ),
    plans: core.serialization.list(PlanGroupPlanDetailResponseData),
    pricingModel: core.serialization.property("pricing_model", core.serialization.string().optional()),
    pricingUrl: core.serialization.property("pricing_url", core.serialization.string().optional()),
});

export declare namespace CatalogConfigurationResponseData {
    export interface Raw {
        add_ons: PlanGroupPlanDetailResponseData.Raw[];
        custom_plan_cta_text?: string | null;
        custom_plan_cta_url?: string | null;
        custom_plan_price_text?: string | null;
        custom_plans_visible: boolean;
        ordered_add_ons: CatalogConfigOrderedPlanResponseData.Raw[];
        ordered_bundles: CatalogConfigOrderedBundleResponseData.Raw[];
        ordered_plans: CatalogConfigOrderedPlanResponseData.Raw[];
        plans: PlanGroupPlanDetailResponseData.Raw[];
        pricing_model?: string | null;
        pricing_url?: string | null;
    }
}
