// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const CatalogConfigOrderedEntitlementResponseData: core.serialization.ObjectSchema<
    serializers.CatalogConfigOrderedEntitlementResponseData.Raw,
    Schematic.CatalogConfigOrderedEntitlementResponseData
> = core.serialization.object({
    featureId: core.serialization.property("feature_id", core.serialization.string()),
    visible: core.serialization.boolean(),
});

export declare namespace CatalogConfigOrderedEntitlementResponseData {
    export interface Raw {
        feature_id: string;
        visible: boolean;
    }
}
