// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const CatalogDerivedFeatureResponseData: core.serialization.ObjectSchema<
    serializers.CatalogDerivedFeatureResponseData.Raw,
    Schematic.CatalogDerivedFeatureResponseData
> = core.serialization.object({
    icon: core.serialization.string(),
    id: core.serialization.string(),
    name: core.serialization.string(),
});

export declare namespace CatalogDerivedFeatureResponseData {
    export interface Raw {
        icon: string;
        id: string;
        name: string;
    }
}
