// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CompanyFeatureUsageExportMetadataSortOrderDirection } from "./CompanyFeatureUsageExportMetadataSortOrderDirection";
import { CompanyFeatureUsageExportMetadataVisibleColumnsItem } from "./CompanyFeatureUsageExportMetadataVisibleColumnsItem";

export const CompanyFeatureUsageExportMetadata: core.serialization.ObjectSchema<
    serializers.CompanyFeatureUsageExportMetadata.Raw,
    Schematic.CompanyFeatureUsageExportMetadata
> = core.serialization.object({
    companyIds: core.serialization.property(
        "company_ids",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    creditTypeIds: core.serialization.property(
        "credit_type_ids",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    featureIds: core.serialization.property(
        "feature_ids",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    hasScheduledDowngrade: core.serialization.property(
        "has_scheduled_downgrade",
        core.serialization.boolean().optional(),
    ),
    monetizedSubscriptions: core.serialization.property(
        "monetized_subscriptions",
        core.serialization.boolean().optional(),
    ),
    notificationEmailRecipientEmailAddresses: core.serialization.property(
        "notification_email_recipient_email_addresses",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    planId: core.serialization.property("plan_id", core.serialization.string().optional()),
    planIds: core.serialization.property("plan_ids", core.serialization.list(core.serialization.string()).optional()),
    planVersionId: core.serialization.property("plan_version_id", core.serialization.string().optional()),
    q: core.serialization.string().optional(),
    sortOrderColumn: core.serialization.property("sort_order_column", core.serialization.string().optional()),
    sortOrderDirection: core.serialization.property(
        "sort_order_direction",
        CompanyFeatureUsageExportMetadataSortOrderDirection.optional(),
    ),
    subscriptionStatuses: core.serialization.property(
        "subscription_statuses",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    subscriptionTypes: core.serialization.property(
        "subscription_types",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    visibleColumns: core.serialization.property(
        "visible_columns",
        core.serialization.list(CompanyFeatureUsageExportMetadataVisibleColumnsItem).optional(),
    ),
    withEntitlementFor: core.serialization.property("with_entitlement_for", core.serialization.string().optional()),
    withSubscription: core.serialization.property("with_subscription", core.serialization.boolean().optional()),
    withoutFeatureOverrideFor: core.serialization.property(
        "without_feature_override_for",
        core.serialization.string().optional(),
    ),
    withoutPlan: core.serialization.property("without_plan", core.serialization.boolean().optional()),
    withoutSubscription: core.serialization.property("without_subscription", core.serialization.boolean().optional()),
});

export declare namespace CompanyFeatureUsageExportMetadata {
    export interface Raw {
        company_ids?: string[] | null;
        credit_type_ids?: string[] | null;
        feature_ids?: string[] | null;
        has_scheduled_downgrade?: boolean | null;
        monetized_subscriptions?: boolean | null;
        notification_email_recipient_email_addresses?: string[] | null;
        plan_id?: string | null;
        plan_ids?: string[] | null;
        plan_version_id?: string | null;
        q?: string | null;
        sort_order_column?: string | null;
        sort_order_direction?: CompanyFeatureUsageExportMetadataSortOrderDirection.Raw | null;
        subscription_statuses?: string[] | null;
        subscription_types?: string[] | null;
        visible_columns?: CompanyFeatureUsageExportMetadataVisibleColumnsItem.Raw[] | null;
        with_entitlement_for?: string | null;
        with_subscription?: boolean | null;
        without_feature_override_for?: string | null;
        without_plan?: boolean | null;
        without_subscription?: boolean | null;
    }
}
