/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Schematic from "../../api/index";
import * as core from "../../core";

export const CompanyLedgerResponseData: core.serialization.ObjectSchema<
    serializers.CompanyLedgerResponseData.Raw,
    Schematic.CompanyLedgerResponseData
> = core.serialization.object({
    id: core.serialization.string(),
    logoUrl: core.serialization.property("logo_url", core.serialization.string().optional()),
    name: core.serialization.string(),
});

export declare namespace CompanyLedgerResponseData {
    export interface Raw {
        id: string;
        logo_url?: string | null;
        name: string;
    }
}
