// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { EntityType } from "./EntityType";

export const ConditionResponseData: core.serialization.ObjectSchema<
    serializers.ConditionResponseData.Raw,
    Schematic.ConditionResponseData
> = core.serialization.object({
    accountId: core.serialization.property("account_id", core.serialization.string()),
    comparisonTraitId: core.serialization.property("comparison_trait_id", core.serialization.string().optional()),
    conditionGroupId: core.serialization.property("condition_group_id", core.serialization.string().optional()),
    conditionType: core.serialization.property("condition_type", core.serialization.string()),
    consumptionRate: core.serialization.property("consumption_rate", core.serialization.number().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    creditId: core.serialization.property("credit_id", core.serialization.string().optional()),
    environmentId: core.serialization.property("environment_id", core.serialization.string()),
    eventSubtype: core.serialization.property("event_subtype", core.serialization.string().optional()),
    flagId: core.serialization.property("flag_id", core.serialization.string().optional()),
    id: core.serialization.string(),
    metricPeriod: core.serialization.property("metric_period", core.serialization.string().optional()),
    metricPeriodMonthReset: core.serialization.property(
        "metric_period_month_reset",
        core.serialization.string().optional(),
    ),
    metricValue: core.serialization.property("metric_value", core.serialization.number().optional()),
    operator: core.serialization.string(),
    resourceUnspecifiedIds: core.serialization.property(
        "resource_unspecified_ids",
        core.serialization.list(core.serialization.string()),
    ),
    ruleId: core.serialization.property("rule_id", core.serialization.string()),
    traitEntityType: core.serialization.property("trait_entity_type", EntityType.optional()),
    traitId: core.serialization.property("trait_id", core.serialization.string().optional()),
    traitValue: core.serialization.property("trait_value", core.serialization.string()),
    traitValueBool: core.serialization.property("trait_value_bool", core.serialization.boolean()),
    traitValueDate: core.serialization.property("trait_value_date", core.serialization.date().optional()),
    traitValueInt: core.serialization.property("trait_value_int", core.serialization.number()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace ConditionResponseData {
    export interface Raw {
        account_id: string;
        comparison_trait_id?: string | null;
        condition_group_id?: string | null;
        condition_type: string;
        consumption_rate?: number | null;
        created_at: string;
        credit_id?: string | null;
        environment_id: string;
        event_subtype?: string | null;
        flag_id?: string | null;
        id: string;
        metric_period?: string | null;
        metric_period_month_reset?: string | null;
        metric_value?: number | null;
        operator: string;
        resource_unspecified_ids: string[];
        rule_id: string;
        trait_entity_type?: EntityType.Raw | null;
        trait_id?: string | null;
        trait_value: string;
        trait_value_bool: boolean;
        trait_value_date?: string | null;
        trait_value_int: number;
        updated_at: string;
    }
}
