// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const CreditCurrencyPriceRequestBody: core.serialization.ObjectSchema<
    serializers.CreditCurrencyPriceRequestBody.Raw,
    Schematic.CreditCurrencyPriceRequestBody
> = core.serialization.object({
    currency: core.serialization.string(),
    pricePerUnit: core.serialization.property("price_per_unit", core.serialization.number().optional()),
    pricePerUnitDecimal: core.serialization.property("price_per_unit_decimal", core.serialization.string().optional()),
});

export declare namespace CreditCurrencyPriceRequestBody {
    export interface Raw {
        currency: string;
        price_per_unit?: number | null;
        price_per_unit_decimal?: string | null;
    }
}
