// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const CreditEventType: core.serialization.Schema<serializers.CreditEventType.Raw, Schematic.CreditEventType> =
    core.serialization.enum_(["grant", "transfer", "usage", "zero_out"]);

export declare namespace CreditEventType {
    export type Raw = "grant" | "transfer" | "usage" | "zero_out";
}
