/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Schematic from "../../api/index";
import * as core from "../../core";

export const CreditGrantExpiryRequestBodyResetType: core.serialization.Schema<
    serializers.CreditGrantExpiryRequestBodyResetType.Raw,
    Schematic.CreditGrantExpiryRequestBodyResetType
> = core.serialization.enum_(["plan_period", "no_reset"]);

export declare namespace CreditGrantExpiryRequestBodyResetType {
    export type Raw = "plan_period" | "no_reset";
}
