/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Schematic from "../../api/index";
import * as core from "../../core";

export const DataExportType: core.serialization.Schema<serializers.DataExportType.Raw, Schematic.DataExportType> =
    core.serialization.stringLiteral("company-feature-usage");

export declare namespace DataExportType {
    export type Raw = "company-feature-usage";
}
