// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { DataExportOutputFileType } from "./DataExportOutputFileType";
import { DataExportStatus } from "./DataExportStatus";
import { DataExportType } from "./DataExportType";

export const DataExportResponseData: core.serialization.ObjectSchema<
    serializers.DataExportResponseData.Raw,
    Schematic.DataExportResponseData
> = core.serialization.object({
    accountId: core.serialization.property("account_id", core.serialization.string()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    environmentId: core.serialization.property("environment_id", core.serialization.string()),
    exportType: core.serialization.property("export_type", DataExportType),
    id: core.serialization.string(),
    metadata: core.serialization.string(),
    outputFileType: core.serialization.property("output_file_type", DataExportOutputFileType),
    status: DataExportStatus,
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace DataExportResponseData {
    export interface Raw {
        account_id: string;
        created_at: string;
        environment_id: string;
        export_type: DataExportType.Raw;
        id: string;
        metadata: string;
        output_file_type: DataExportOutputFileType.Raw;
        status: DataExportStatus.Raw;
        updated_at: string;
    }
}
