/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Schematic from "../../api/index";
import * as core from "../../core";

export const FlagResponseData: core.serialization.ObjectSchema<
    serializers.FlagResponseData.Raw,
    Schematic.FlagResponseData
> = core.serialization.object({
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    defaultValue: core.serialization.property("default_value", core.serialization.boolean()),
    description: core.serialization.string(),
    featureId: core.serialization.property("feature_id", core.serialization.string().optional()),
    flagType: core.serialization.property("flag_type", core.serialization.string()),
    id: core.serialization.string(),
    key: core.serialization.string(),
    maintainerId: core.serialization.property("maintainer_id", core.serialization.string().optional()),
    name: core.serialization.string(),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace FlagResponseData {
    export interface Raw {
        created_at: string;
        default_value: boolean;
        description: string;
        feature_id?: string | null;
        flag_type: string;
        id: string;
        key: string;
        maintainer_id?: string | null;
        name: string;
        updated_at: string;
    }
}
