/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Schematic from "../../api/index";
import * as core from "../../core";
import { PlanSelection } from "./PlanSelection";
import { UpdateCreditBundleRequestBody } from "./UpdateCreditBundleRequestBody";
import { UpdatePayInAdvanceRequestBody } from "./UpdatePayInAdvanceRequestBody";

export const ManagePlanRequest: core.serialization.ObjectSchema<
    serializers.ManagePlanRequest.Raw,
    Schematic.ManagePlanRequest
> = core.serialization.object({
    addOnSelections: core.serialization.property("add_on_selections", core.serialization.list(PlanSelection)),
    basePlanId: core.serialization.property("base_plan_id", core.serialization.string().optional()),
    basePlanPriceId: core.serialization.property("base_plan_price_id", core.serialization.string().optional()),
    cancelImmediately: core.serialization.property("cancel_immediately", core.serialization.boolean().optional()),
    companyId: core.serialization.property("company_id", core.serialization.string()),
    couponExternalId: core.serialization.property("coupon_external_id", core.serialization.string().optional()),
    creditBundles: core.serialization.property(
        "credit_bundles",
        core.serialization.list(UpdateCreditBundleRequestBody),
    ),
    payInAdvanceEntitlements: core.serialization.property(
        "pay_in_advance_entitlements",
        core.serialization.list(UpdatePayInAdvanceRequestBody),
    ),
    paymentMethodExternalId: core.serialization.property(
        "payment_method_external_id",
        core.serialization.string().optional(),
    ),
    promoCode: core.serialization.property("promo_code", core.serialization.string().optional()),
    prorate: core.serialization.boolean().optional(),
});

export declare namespace ManagePlanRequest {
    export interface Raw {
        add_on_selections: PlanSelection.Raw[];
        base_plan_id?: string | null;
        base_plan_price_id?: string | null;
        cancel_immediately?: boolean | null;
        company_id: string;
        coupon_external_id?: string | null;
        credit_bundles: UpdateCreditBundleRequestBody.Raw[];
        pay_in_advance_entitlements: UpdatePayInAdvanceRequestBody.Raw[];
        payment_method_external_id?: string | null;
        promo_code?: string | null;
        prorate?: boolean | null;
    }
}
