/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Schematic from "../../api/index";
import * as core from "../../core";

export const PaginationFilter: core.serialization.ObjectSchema<
    serializers.PaginationFilter.Raw,
    Schematic.PaginationFilter
> = core.serialization.object({
    limit: core.serialization.number().optional(),
    offset: core.serialization.number().optional(),
});

export declare namespace PaginationFilter {
    interface Raw {
        limit?: number | null;
        offset?: number | null;
    }
}
