// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { BillingLinkedResourceResponseData } from "./BillingLinkedResourceResponseData";
import { BillingPlanCreditGrantResponseData } from "./BillingPlanCreditGrantResponseData";
import { BillingPriceResponseData } from "./BillingPriceResponseData";
import { BillingProductDetailResponseData } from "./BillingProductDetailResponseData";
import { ChargeType } from "./ChargeType";
import { CustomPlanViewConfigResponseData } from "./CustomPlanViewConfigResponseData";
import { FeatureDetailResponseData } from "./FeatureDetailResponseData";
import { PlanCurrencyPricesResponseData } from "./PlanCurrencyPricesResponseData";
import { PlanEntitlementResponseData } from "./PlanEntitlementResponseData";
import { PlanIcon } from "./PlanIcon";
import { PlanType } from "./PlanType";
import { PlanVersionResponseData } from "./PlanVersionResponseData";

export const PlanGroupPlanDetailResponseData: core.serialization.ObjectSchema<
    serializers.PlanGroupPlanDetailResponseData.Raw,
    Schematic.PlanGroupPlanDetailResponseData
> = core.serialization.object({
    activeVersion: core.serialization.property("active_version", PlanVersionResponseData.optional()),
    audienceType: core.serialization.property("audience_type", core.serialization.string().optional()),
    billingLinkedResource: core.serialization.property(
        "billing_linked_resource",
        BillingLinkedResourceResponseData.optional(),
    ),
    billingProduct: core.serialization.property("billing_product", BillingProductDetailResponseData.optional()),
    chargeType: core.serialization.property("charge_type", ChargeType),
    companyCount: core.serialization.property("company_count", core.serialization.number()),
    companyId: core.serialization.property("company_id", core.serialization.string().optional()),
    companyName: core.serialization.property("company_name", core.serialization.string().optional()),
    compatiblePlanIds: core.serialization.property(
        "compatible_plan_ids",
        core.serialization.list(core.serialization.string()),
    ),
    controlledBy: core.serialization.property("controlled_by", core.serialization.string()),
    copiedFromPlanId: core.serialization.property("copied_from_plan_id", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    currencyPrices: core.serialization.property(
        "currency_prices",
        core.serialization.list(PlanCurrencyPricesResponseData),
    ),
    customPlanConfig: core.serialization.property("custom_plan_config", CustomPlanViewConfigResponseData.optional()),
    description: core.serialization.string(),
    draftVersion: core.serialization.property("draft_version", PlanVersionResponseData.optional()),
    entitlements: core.serialization.list(PlanEntitlementResponseData),
    features: core.serialization.list(FeatureDetailResponseData),
    icon: PlanIcon,
    id: core.serialization.string(),
    includedCreditGrants: core.serialization.property(
        "included_credit_grants",
        core.serialization.list(BillingPlanCreditGrantResponseData).optional(),
    ),
    isCustom: core.serialization.property("is_custom", core.serialization.boolean()),
    isDefault: core.serialization.property("is_default", core.serialization.boolean()),
    isFree: core.serialization.property("is_free", core.serialization.boolean()),
    isTrialable: core.serialization.property("is_trialable", core.serialization.boolean()),
    monthlyPrice: core.serialization.property("monthly_price", BillingPriceResponseData.optional()),
    name: core.serialization.string(),
    oneTimePrice: core.serialization.property("one_time_price", BillingPriceResponseData.optional()),
    planType: core.serialization.property("plan_type", PlanType),
    trialDays: core.serialization.property("trial_days", core.serialization.number().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    versions: core.serialization.list(PlanVersionResponseData),
    yearlyPrice: core.serialization.property("yearly_price", BillingPriceResponseData.optional()),
});

export declare namespace PlanGroupPlanDetailResponseData {
    export interface Raw {
        active_version?: PlanVersionResponseData.Raw | null;
        audience_type?: string | null;
        billing_linked_resource?: BillingLinkedResourceResponseData.Raw | null;
        billing_product?: BillingProductDetailResponseData.Raw | null;
        charge_type: ChargeType.Raw;
        company_count: number;
        company_id?: string | null;
        company_name?: string | null;
        compatible_plan_ids: string[];
        controlled_by: string;
        copied_from_plan_id?: string | null;
        created_at: string;
        currency_prices: PlanCurrencyPricesResponseData.Raw[];
        custom_plan_config?: CustomPlanViewConfigResponseData.Raw | null;
        description: string;
        draft_version?: PlanVersionResponseData.Raw | null;
        entitlements: PlanEntitlementResponseData.Raw[];
        features: FeatureDetailResponseData.Raw[];
        icon: PlanIcon.Raw;
        id: string;
        included_credit_grants?: BillingPlanCreditGrantResponseData.Raw[] | null;
        is_custom: boolean;
        is_default: boolean;
        is_free: boolean;
        is_trialable: boolean;
        monthly_price?: BillingPriceResponseData.Raw | null;
        name: string;
        one_time_price?: BillingPriceResponseData.Raw | null;
        plan_type: PlanType.Raw;
        trial_days?: number | null;
        updated_at: string;
        versions: PlanVersionResponseData.Raw[];
        yearly_price?: BillingPriceResponseData.Raw | null;
    }
}
