/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Schematic from "../../api/index";
import * as core from "../../core";
import { RawEventResponseData } from "./RawEventResponseData";

export const RawEventBatchResponseData: core.serialization.ObjectSchema<
  serializers.RawEventBatchResponseData.Raw,
  Schematic.RawEventBatchResponseData
> = core.serialization.object({
  events: core.serialization.list(RawEventResponseData),
});

export declare namespace RawEventBatchResponseData {
  interface Raw {
    events: RawEventResponseData.Raw[];
  }
}
