// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const RuleConditionGroupResponseData: core.serialization.ObjectSchema<
    serializers.RuleConditionGroupResponseData.Raw,
    Schematic.RuleConditionGroupResponseData
> = core.serialization.object({
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    environmentId: core.serialization.property("environment_id", core.serialization.string()),
    flagId: core.serialization.property("flag_id", core.serialization.string().optional()),
    id: core.serialization.string(),
    ruleId: core.serialization.property("rule_id", core.serialization.string()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace RuleConditionGroupResponseData {
    export interface Raw {
        created_at: string;
        environment_id: string;
        flag_id?: string | null;
        id: string;
        rule_id: string;
        updated_at: string;
    }
}
