// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { RuleConditionDetailResponseData } from "./RuleConditionDetailResponseData";

export const RuleConditionGroupDetailResponseData: core.serialization.ObjectSchema<
    serializers.RuleConditionGroupDetailResponseData.Raw,
    Schematic.RuleConditionGroupDetailResponseData
> = core.serialization.object({
    conditions: core.serialization.list(RuleConditionDetailResponseData),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    environmentId: core.serialization.property("environment_id", core.serialization.string()),
    flagId: core.serialization.property("flag_id", core.serialization.string().optional()),
    id: core.serialization.string(),
    ruleId: core.serialization.property("rule_id", core.serialization.string()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace RuleConditionGroupDetailResponseData {
    export interface Raw {
        conditions: RuleConditionDetailResponseData.Raw[];
        created_at: string;
        environment_id: string;
        flag_id?: string | null;
        id: string;
        rule_id: string;
        updated_at: string;
    }
}
