// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { RulesengineCreditSpendPolicyScope } from "./RulesengineCreditSpendPolicyScope";
import { RulesengineCreditSpendWindow } from "./RulesengineCreditSpendWindow";

export const RulesengineCreditSpendPolicy: core.serialization.ObjectSchema<
    serializers.RulesengineCreditSpendPolicy.Raw,
    Schematic.RulesengineCreditSpendPolicy
> = core.serialization.object({
    consumed: core.serialization.number().optional(),
    creditId: core.serialization.property("credit_id", core.serialization.string()),
    id: core.serialization.string(),
    kind: core.serialization.string(),
    label: core.serialization.string().optional(),
    limit: core.serialization.number(),
    resetsAt: core.serialization.property("resets_at", core.serialization.date().optional()),
    scope: RulesengineCreditSpendPolicyScope,
    window: RulesengineCreditSpendWindow.optional(),
});

export declare namespace RulesengineCreditSpendPolicy {
    export interface Raw {
        consumed?: number | null;
        credit_id: string;
        id: string;
        kind: string;
        label?: string | null;
        limit: number;
        resets_at?: string | null;
        scope: RulesengineCreditSpendPolicyScope.Raw;
        window?: RulesengineCreditSpendWindow.Raw | null;
    }
}
