/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Schematic from "../../api/index";
import * as core from "../../core";

export const RulesengineEntityType: core.serialization.Schema<
    serializers.RulesengineEntityType.Raw,
    Schematic.RulesengineEntityType
> = core.serialization.enum_(["company", "user"]);

export declare namespace RulesengineEntityType {
    export type Raw = "company" | "user";
}
