// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const RulesEngineSchemaVersion: core.serialization.Schema<
    serializers.RulesEngineSchemaVersion.Raw,
    Schematic.RulesEngineSchemaVersion
> = core.serialization.enum_(["vf05bf5da", "placeholder-for-fern-compatibility"]);

export declare namespace RulesEngineSchemaVersion {
    export type Raw = "vf05bf5da" | "placeholder-for-fern-compatibility";
}
