// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ScheduledDowngradeResponseData: core.serialization.ObjectSchema<
    serializers.ScheduledDowngradeResponseData.Raw,
    Schematic.ScheduledDowngradeResponseData
> = core.serialization.object({
    currency: core.serialization.string(),
    effectiveAfter: core.serialization.property("effective_after", core.serialization.date()),
    fromPlanId: core.serialization.property("from_plan_id", core.serialization.string()),
    fromPlanName: core.serialization.property("from_plan_name", core.serialization.string()),
    fromSubscriptionPrice: core.serialization.property("from_subscription_price", core.serialization.number()),
    id: core.serialization.string(),
    interval: core.serialization.string(),
    scheduledInterval: core.serialization.property("scheduled_interval", core.serialization.string().optional()),
    scheduledPrice: core.serialization.property("scheduled_price", core.serialization.number().optional()),
    toPlanId: core.serialization.property("to_plan_id", core.serialization.string()),
    toPlanName: core.serialization.property("to_plan_name", core.serialization.string()),
});

export declare namespace ScheduledDowngradeResponseData {
    export interface Raw {
        currency: string;
        effective_after: string;
        from_plan_id: string;
        from_plan_name: string;
        from_subscription_price: number;
        id: string;
        interval: string;
        scheduled_interval?: string | null;
        scheduled_price?: number | null;
        to_plan_id: string;
        to_plan_name: string;
    }
}
