// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const StripeIntegrationConfig: core.serialization.ObjectSchema<
    serializers.StripeIntegrationConfig.Raw,
    Schematic.StripeIntegrationConfig
> = core.serialization.object({
    accountId: core.serialization.property("account_id", core.serialization.string().optional()),
    accountName: core.serialization.property("account_name", core.serialization.string().optional()),
    companyUpdateOnly: core.serialization.property("company_update_only", core.serialization.boolean().optional()),
    isSandbox: core.serialization.property("is_sandbox", core.serialization.boolean()),
    liveMode: core.serialization.property("live_mode", core.serialization.boolean()),
    onboardUrl: core.serialization.property("onboard_url", core.serialization.string().optional()),
    version: core.serialization.number(),
});

export declare namespace StripeIntegrationConfig {
    export interface Raw {
        account_id?: string | null;
        account_name?: string | null;
        company_update_only?: boolean | null;
        is_sandbox: boolean;
        live_mode: boolean;
        onboard_url?: string | null;
        version: number;
    }
}
