// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const TimeSeriesGranularity: core.serialization.Schema<
    serializers.TimeSeriesGranularity.Raw,
    Schematic.TimeSeriesGranularity
> = core.serialization.enum_(["daily", "hourly", "monthly", "weekly"]);

export declare namespace TimeSeriesGranularity {
    export type Raw = "daily" | "hourly" | "monthly" | "weekly";
}
