// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";
import { CreateCustomPlanBundlePlanRequestBody } from "../../../../types/CreateCustomPlanBundlePlanRequestBody";
import { PlanBundleCreditGrantRequestBody } from "../../../../types/PlanBundleCreditGrantRequestBody";
import { PlanBundleEntitlementRequestBody } from "../../../../types/PlanBundleEntitlementRequestBody";
import { UpsertBillingProductRequestBody } from "../../../../types/UpsertBillingProductRequestBody";

export const CreateCustomPlanBundleRequestBody: core.serialization.Schema<
    serializers.CreateCustomPlanBundleRequestBody.Raw,
    Schematic.CreateCustomPlanBundleRequestBody
> = core.serialization.object({
    billingProduct: core.serialization.property("billing_product", UpsertBillingProductRequestBody),
    creditGrants: core.serialization.property(
        "credit_grants",
        core.serialization.list(PlanBundleCreditGrantRequestBody).optional(),
    ),
    entitlements: core.serialization.list(PlanBundleEntitlementRequestBody),
    plan: CreateCustomPlanBundlePlanRequestBody,
});

export declare namespace CreateCustomPlanBundleRequestBody {
    export interface Raw {
        billing_product: UpsertBillingProductRequestBody.Raw;
        credit_grants?: PlanBundleCreditGrantRequestBody.Raw[] | null;
        entitlements: PlanBundleEntitlementRequestBody.Raw[];
        plan: CreateCustomPlanBundlePlanRequestBody.Raw;
    }
}
