// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { PlanVersionCompanyMigrationResponseData } from "../../../types/PlanVersionCompanyMigrationResponseData";
import { ListCompanyMigrationsParams } from "./ListCompanyMigrationsParams";

export const ListCompanyMigrationsResponse: core.serialization.ObjectSchema<
    serializers.ListCompanyMigrationsResponse.Raw,
    Schematic.ListCompanyMigrationsResponse
> = core.serialization.object({
    data: core.serialization.list(PlanVersionCompanyMigrationResponseData),
    params: ListCompanyMigrationsParams,
});

export declare namespace ListCompanyMigrationsResponse {
    export interface Raw {
        data: PlanVersionCompanyMigrationResponseData.Raw[];
        params: ListCompanyMigrationsParams.Raw;
    }
}
