/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         companyId: "company_id",
 *         eventSubtype: "event_subtype",
 *         flagId: "flag_id",
 *         userId: "user_id",
 *         limit: 1,
 *         offset: 1
 *     }
 */
export interface ListEventsRequest {
    companyId?: string;
    eventSubtype?: string;
    eventTypes?: Schematic.ListEventsRequestEventTypesItem | Schematic.ListEventsRequestEventTypesItem[];
    flagId?: string;
    userId?: string;
    /**
     * Page limit (default 100)
     */
    limit?: number;
    /**
     * Page offset (default 0)
     */
    offset?: number;
}
