/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListEventsRequest {
  companyId?: string;
  eventSubtype?: string;
  eventTypes?: string | string[];
  flagId?: string;
  userId?: string;
  /**
   * Page limit (default 100)
   */
  limit?: number;
  /**
   * Page offset (default 0)
   */
  offset?: number;
}
