// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { TimeSeriesGranularity } from "../../../types/TimeSeriesGranularity";

export const GetEnvironmentTraitUsageTimeSeriesParams: core.serialization.ObjectSchema<
    serializers.GetEnvironmentTraitUsageTimeSeriesParams.Raw,
    Schematic.GetEnvironmentTraitUsageTimeSeriesParams
> = core.serialization.object({
    endTime: core.serialization.property("end_time", core.serialization.date().optional()),
    featureId: core.serialization.property("feature_id", core.serialization.string().optional()),
    granularity: TimeSeriesGranularity.optional(),
    startTime: core.serialization.property("start_time", core.serialization.date().optional()),
});

export declare namespace GetEnvironmentTraitUsageTimeSeriesParams {
    export interface Raw {
        end_time?: string | null;
        feature_id?: string | null;
        granularity?: TimeSeriesGranularity.Raw | null;
        start_time?: string | null;
    }
}
