// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index";

export interface PreviewManagePlanResponse {
    data: Schematic.ManagePlanPreviewResponseResponseData;
    /** Input parameters */
    params: Record<string, unknown>;
}
