/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Filter by plan type
 */
export type CountPlansResponseParamsPlanType = "plan" | "add_on";
export const CountPlansResponseParamsPlanType = {
    Plan: "plan",
    AddOn: "add_on",
} as const;
