/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreatePlanRequestBodyPlanType = "plan" | "add_on";

export const CreatePlanRequestBodyPlanType = {
  Plan: "plan",
  AddOn: "add_on",
} as const;
