/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Input parameters
 */
export interface ListPlansParams {
  companyId?: string;
  ids?: string[];
  /** Page limit (default 100) */
  limit?: number;
  /** Page offset (default 0) */
  offset?: number;
  q?: string;
  /** Filter out plans that already have a plan entitlement for the specified feature ID */
  withoutEntitlementFor?: string;
}
