/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../index.js";

export interface ListInvoicesResponse {
    /** The returned resources */
    data: Schematic.InvoiceResponseData[];
    /** Input parameters */
    params: ListInvoicesResponse.Params;
}

export namespace ListInvoicesResponse {
    /**
     * Input parameters
     */
    export interface Params {
        company_id?: string;
        customer_external_id?: string;
        /** Page limit (default 100) */
        limit?: number;
        /** Page offset (default 0) */
        offset?: number;
        subscription_external_id?: string;
    }
}
