// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index.js";

export interface ListCouponsResponse {
    data: Schematic.BillingCouponResponseData[];
    /** Input parameters */
    params: ListCouponsResponse.Params;
}

export namespace ListCouponsResponse {
    /**
     * Input parameters
     */
    export interface Params {
        is_active?: boolean;
        /** Page limit (default 100) */
        limit?: number;
        /** Page offset (default 0) */
        offset?: number;
        q?: string;
    }
}
