/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ListBillingProductPricesRequestTiersMode = "volume" | "graduated";
export const ListBillingProductPricesRequestTiersMode = {
    Volume: "volume",
    Graduated: "graduated",
} as const;
