// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index";

export interface ListPlanEntitlementsResponse {
    data: Schematic.PlanEntitlementResponseData[];
    /** Input parameters */
    params: Schematic.ListPlanEntitlementsParams;
}
