// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index";

/**
 * Input parameters
 */
export interface ListFeatureUsageParams {
    companyId?: string;
    companyKeys?: Record<string, string>;
    featureIds?: string[];
    /** Include time-bucketed usage aggregation (today, this week, this month, billing period) for credit-based entitlements. Defaults to false for performance. */
    includeUsageAggregation?: boolean;
    /** Page limit (default 100) */
    limit?: number;
    /** Filter for features managed by a billing provider, or by Schematic (no billing provider) */
    managedBy?: Schematic.BillingProviderType;
    /** Page offset (default 0) */
    offset?: number;
    q?: string;
    withoutNegativeEntitlements?: boolean;
}
