// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index";

/**
 * Input parameters
 */
export interface ListCompanyUserUsageParams {
    /** Company to break usage down for */
    companyId?: string;
    /** End of the usage window (exclusive); defaults to now */
    endTime?: Date;
    /** The event-based feature to break down; required when metric is feature */
    featureId?: string;
    /** Page limit (default 100) */
    limit?: number;
    /** Which metric to break usage down by */
    metric?: Schematic.UserUsageMetric;
    /** Page offset (default 0) */
    offset?: number;
    /** Start of the usage window; defaults to 30 days before the end */
    startTime?: Date;
}
