// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index";

export interface ListCompanyUserUsageResponse {
    data: Schematic.CompanyUserUsageResponseData;
    /** Input parameters */
    params: Schematic.ListCompanyUserUsageParams;
}
