// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index";

export interface ListFeatureCompaniesResponse {
    data: Schematic.FeatureCompanyResponseData[];
    /** Input parameters */
    params: Schematic.ListFeatureCompaniesParams;
}
