// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         companyId: "company_id",
 *         creditId: "credit_id",
 *         quantity: 1000000,
 *         reason: "adjustment"
 *     }
 */
export interface CreateCompanyCreditGrant {
    billingPeriodsCount?: number;
    companyId: string;
    creditId: string;
    currency?: string;
    expiresAt?: Date;
    expiryType?: Schematic.BillingCreditExpiryType;
    expiryUnit?: Schematic.BillingCreditExpiryUnit;
    expiryUnitCount?: number;
    quantity: number;
    reason: Schematic.BillingCreditGrantReason;
    renewalEnabled?: boolean;
    renewalPeriod?: Schematic.BillingPlanCreditGrantResetStart;
}
