// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         companyId: "company_id",
 *         order: "created_at",
 *         dir: "asc",
 *         limit: 1000000,
 *         offset: 1000000
 *     }
 */
export interface ListCompanyGrantsRequest {
    companyId?: string;
    order?: Schematic.CreditGrantSortOrder;
    dir?: Schematic.SortDirection;
    /** Page limit (default 100) */
    limit?: number;
    /** Page offset (default 0) */
    offset?: number;
}
