/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ListCompanyGrantsRequest {
    companyId?: string;
    order?: Schematic.ListCompanyGrantsRequestOrder;
    dir?: Schematic.ListCompanyGrantsRequestDir;
    /**
     * Page limit (default 100)
     */
    limit?: number;
    /**
     * Page offset (default 0)
     */
    offset?: number;
}
