/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         bundleName: "bundle_name",
 *         pricePerUnit: 1
 *     }
 */
export interface UpdateCreditBundleDetailsRequestBody {
    bundleName: string;
    expiryType?: Schematic.UpdateCreditBundleDetailsRequestBodyExpiryType;
    expiryUnit?: Schematic.UpdateCreditBundleDetailsRequestBodyExpiryUnit;
    expiryUnitCount?: number;
    pricePerUnit: number;
    pricePerUnitDecimal?: string;
    quantity?: number;
    status?: Schematic.UpdateCreditBundleDetailsRequestBodyStatus;
}
