/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Schematic from "../../../../index";

/**
 * @example
 *     {
 *         description: "description",
 *         name: "name"
 *     }
 */
export interface UpdateBillingCreditRequestBody {
    burnStrategy?: Schematic.UpdateBillingCreditRequestBodyBurnStrategy;
    defaultExpiryUnit?: "days";
    defaultExpiryUnitCount?: number;
    defaultRolloverPolicy?: Schematic.UpdateBillingCreditRequestBodyDefaultRolloverPolicy;
    description: string;
    icon?: string;
    name: string;
    perUnitPrice?: number;
    perUnitPriceDecimal?: string;
    pluralName?: string;
    singularName?: string;
}
