// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { IntegrationsDataSetResponseData } from "../../../types/IntegrationsDataSetResponseData";

export const LoadSampleDataSetResponse: core.serialization.ObjectSchema<
    serializers.LoadSampleDataSetResponse.Raw,
    Schematic.LoadSampleDataSetResponse
> = core.serialization.object({
    data: IntegrationsDataSetResponseData,
    params: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace LoadSampleDataSetResponse {
    export interface Raw {
        data: IntegrationsDataSetResponseData.Raw;
        params: Record<string, unknown>;
    }
}
