// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { CheckAndReserveFlagResponseData } from "../../../types/CheckAndReserveFlagResponseData";

export const CheckAndReserveFlagResponse: core.serialization.ObjectSchema<
    serializers.CheckAndReserveFlagResponse.Raw,
    Schematic.CheckAndReserveFlagResponse
> = core.serialization.object({
    data: CheckAndReserveFlagResponseData,
    params: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace CheckAndReserveFlagResponse {
    export interface Raw {
        data: CheckAndReserveFlagResponseData.Raw;
        params: Record<string, unknown>;
    }
}
