/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import { CountResponse } from "../../../types/CountResponse";
import { CountApiRequestsParams } from "./CountApiRequestsParams";

export const CountApiRequestsResponse: core.serialization.ObjectSchema<
    serializers.CountApiRequestsResponse.Raw,
    Schematic.CountApiRequestsResponse
> = core.serialization.object({
    data: CountResponse,
    params: CountApiRequestsParams,
});

export declare namespace CountApiRequestsResponse {
    interface Raw {
        data: CountResponse.Raw;
        params: CountApiRequestsParams.Raw;
    }
}
