// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { AuditLogResponseData } from "../../../types/AuditLogResponseData";

export const GetAuditLogResponse: core.serialization.ObjectSchema<
    serializers.GetAuditLogResponse.Raw,
    Schematic.GetAuditLogResponse
> = core.serialization.object({
    data: AuditLogResponseData,
    params: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace GetAuditLogResponse {
    export interface Raw {
        data: AuditLogResponseData.Raw;
        params: Record<string, unknown>;
    }
}
