// This file was auto-generated by Fern from our API Definition.

import type * as Schematic from "../../../index";

export interface CountCreditBundlesResponse {
    data: Schematic.CountResponse;
    /** Input parameters */
    params: Schematic.CountCreditBundlesParams;
}
