/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateCreditBundleRequestBodyStatus = "active" | "inactive";
export const CreateCreditBundleRequestBodyStatus = {
    Active: "active",
    Inactive: "inactive",
} as const;
