/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ListCompanyGrantsRequestDir = "asc" | "desc";
export const ListCompanyGrantsRequestDir = {
    Asc: "asc",
    Desc: "desc",
} as const;
