/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateBillingPlanCreditGrantRequestBodyResetCadence = "monthly" | "yearly" | "daily" | "weekly";
export const UpdateBillingPlanCreditGrantRequestBodyResetCadence = {
    Monthly: "monthly",
    Yearly: "yearly",
    Daily: "daily",
    Weekly: "weekly",
} as const;
